apiVersion: v1
kind: Service
metadata:
  name: quakewatch-service
  labels:
    app: quakewatch
spec:
  type: LoadBalancer
  selector:
    app: quakewatch
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http
